CREATE TABLE "GCG_4010_CON_StrpLst"(
 "Week_No" CHAR(10),
 "Order_No" CHAR(10),
 "Customer_Name" CHAR(50),
 "AZ" CHAR(20),
 "CZ" CHAR(20),
 "FZ" CHAR(20),
 "HZ" CHAR(20),
 "RZ" CHAR(20),
 "SZ" CHAR(20),
 "MZ" CHAR(20),
 "BZ" CHAR(20),
 "SalesPerson" CHAR(5),
 "State" CHAR(5),
 "BIRUNID" BIGINT,
 "AZ_Close" CHAR(1),
 "CZ_Close" CHAR(1),
 "FZ_Close" CHAR(1),
 "HZ_Close" CHAR(1),
 "RZ_Close" CHAR(1),
 "SZ_Close" CHAR(1),
 "MZ_Close" CHAR(1),
 "BZ_Close" CHAR(1),
 "Comments" CHAR(50),
 "GS_OrderNo" CHAR(12),
 "Total_Order" DECIMAL(20,2) );
